"use client"

import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google'
import SSRProvider from 'react-bootstrap/SSRProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cygnustisc',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
      </head >
      <body className={inter.className}><SSRProvider>{children}</SSRProvider></body>
    </html>
  )
}
